// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {ui} from '../models';

export function ConnectAll():Promise<void>;

export function ConnectTunnel(arg1:string):Promise<void>;

export function DetectMode():Promise<string>;

export function DisconnectAll():Promise<void>;

export function DisconnectTunnel(arg1:string):Promise<void>;

export function FetchGroups(arg1:string):Promise<Array<string>>;

export function Version():Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetLogs():Promise<Array<ui.LogEntry>>;

export function GetMode():Promise<string>;

export function GetTunnelStatus(arg1:string):Promise<ui.TunnelStatus>;

export function GetTunnels():Promise<Array<config.Tunnel>>;

export function IsAdmin():Promise<boolean>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function Submit2FA(arg1:string,arg2:string):Promise<void>;

export function SwitchMode(arg1:string):Promise<void>;

export function PACURL():Promise<string>;

export function PACScript():Promise<string>;
