// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectAll() {
  return window['go']['ui']['App']['ConnectAll']();
}

export function ConnectTunnel(arg1) {
  return window['go']['ui']['App']['ConnectTunnel'](arg1);
}

export function DetectMode() {
  return window['go']['ui']['App']['DetectMode']();
}

export function DisconnectAll() {
  return window['go']['ui']['App']['DisconnectAll']();
}

export function DisconnectTunnel(arg1) {
  return window['go']['ui']['App']['DisconnectTunnel'](arg1);
}

export function Version() {
  return window['go']['ui']['App']['Version']();
}

export function FetchGroups(arg1) {
  return window['go']['ui']['App']['FetchGroups'](arg1);
}

export function GetConfig() {
  return window['go']['ui']['App']['GetConfig']();
}

export function GetLogs() {
  return window['go']['ui']['App']['GetLogs']();
}

export function GetMode() {
  return window['go']['ui']['App']['GetMode']();
}

export function GetTunnelStatus(arg1) {
  return window['go']['ui']['App']['GetTunnelStatus'](arg1);
}

export function GetTunnels() {
  return window['go']['ui']['App']['GetTunnels']();
}

export function IsAdmin() {
  return window['go']['ui']['App']['IsAdmin']();
}

export function SaveConfig(arg1) {
  return window['go']['ui']['App']['SaveConfig'](arg1);
}

export function Submit2FA(arg1, arg2) {
  return window['go']['ui']['App']['Submit2FA'](arg1, arg2);
}

export function SwitchMode(arg1) {
  return window['go']['ui']['App']['SwitchMode'](arg1);
}

export function PACURL() {
  return window['go']['ui']['App']['PACURL']();
}

export function PACScript() {
  return window['go']['ui']['App']['PACScript']();
}

export function ApplySystemProxy() {
  return window['go']['ui']['App']['ApplySystemProxy']();
}

export function ClearSystemProxy() {
  return window['go']['ui']['App']['ClearSystemProxy']();
}

export function SystemProxyApplied() {
  return window['go']['ui']['App']['SystemProxyApplied']();
}

export function RestartAsAdmin() {
  return window['go']['ui']['App']['RestartAsAdmin']();
}

export function NeedsAdminMessage() {
  return window['go']['ui']['App']['NeedsAdminMessage']();
}
